server:
  port: 8088                #配置端口号默认为 8080

# mysql路径，用户名、密码 以及驱动类
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&amp
    username: root
    password: wang123

# REDIS (RedisProperties)
  redis:
    database: 0            # Redis数据库索引（默认为0）
    host: 192.168.183.128  # Redis服务器地址
    port: 6379             # Redis服务器连接端口
    password: 123456      # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8   # 连接池中的最大空闲连接
      min-idle: 0   # 连接池中的最小空闲连接
    timeout: 0      # 连接超时时间（毫秒）

##################重复提交限制时间################
samecommit:
    time-out-time: 10