# 富文本上传图片后显示本地图片配置，增加映射
image:
  upload-path: /opt/upload-path/

# 资源文件上传路径
resource:
    upload-path: /opt/resource-file/

server:
  port: 8088                #配置端口号

# mysql路径，用户名、密码 以及驱动类
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/my_blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&amp
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  mvc:
      static-path-pattern: /**
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${image.upload-path},file:${resource.upload-path}

##################重复提交限制时间和请求接口频率次数限制################
commit:
    time-out-time: 10
    commit-count: 20
