#server:
#  error:
#  path: /error/404.html

# 环境 dev|test|pro
spring:
  profiles:
    active: dev

# Mybatis配置
mybatis-plus:
  mapperLocations: classpath:/mappers/**/*.xml
  type-aliases-package: com.blob.pojo.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    refresh-mapper: true
  # 刷新mapper调试神器
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false